### ISSUE TITLE
Strange error with rules involving RDF*

### ISSUE THREAD

**Issue by pchampin** [eyereasoner/eye#10]
I tried to reduce it to a minimal example:
```
{} => { << :s :p :o >> :c :c2 }.
{} => { << :s :p :o >> :c :c2, :c3 }.
{ << :s :p :o >> :c :c2 } <= {}.
#{ << :s :p :o >> :c :c2, :c3 } <= {}. # this one raises an error
```
The three first rules work, but uncommenting the 4th one causes the following error:
```
** ERROR ** gre ** error(permission_error(modify,static_procedure,(,)/2),context(system:assertz/1,_5824))
```

**Comment by josd** [comment]
Thanks for testing @pchampin 
In the current implementation of EYE, the conclusion part of backward rules (that is rules using <=) has
te same restriction as the "head" of a Prolog rule. So conjunctions are not allowed hence the (,)/2 error message
(the , is conjunction in Prolog).
In a sense it is good to look to backward rules as "soft" built-ins like the examples in https://github.com/josd/eye/blob/master/reasoning/n3c/components.n3

**Comment by pchampin** [comment]
Damn, I never realized that!
It has nothing to do with RDF*, then, and my example was *not* minimal...
Sorry about the noise.
