### ISSUE TITLE
Incorrect installation documentation

### ISSUE THREAD

**Issue by dzaleskis** [eyereasoner/eye#100]
The `INSTALL` file (https://github.com/eyereasoner/eye/blob/master/INSTALL#L19) says that the default prefix for installation is `usr/local` but actually it is `opt/eye` (see https://github.com/eyereasoner/eye/blob/master/install.sh#L6).

This is a bit confusing for new users like me, it would be nice to make these match.

**Comment by josd** [comment]
Thanks and it is now fixed.
