### ISSUE TITLE
Redundant `initialization/1` directive wrapper

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#11]
In the following line, the `initialization/1` directive wrapper is not necessary as `set_prolog_flag/2` is a standard directive.

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L8

**Comment by josd** [comment]
Thank you very much @pmoura and this issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1548
