### ISSUE TITLE
RDF Surfaces won't work

### ISSUE THREAD

**Issue by renyuneyun** [eyereasoner/eye#112]
I recently updated my eye version, and found that `--blogic` switch is gone. I found [the document](https://github.com/eyereasoner/eye/blob/master/documentation/blogic.md). The document says adding `--no-bnode-relabeling` is needed for RDF Surfaces. However, even if using the example command (containing this switch), the example Socrates file doesn't work either.

Is there anything else needed?

**Comment by josd** [comment]
The documentation is now updated and queries are now like
```
# Define what to send to the output
(_:S _:O) log:onNegativeSurface {
    _:S a _:O .
    () log:onNegativeAnswerSurface {
        _:S a _:O .
    } .
} .
```

**Comment by renyuneyun** [comment]
Thanks. That works now!
