### ISSUE TITLE
Empty graph and `--entail` and `--not-entail`

### ISSUE THREAD

**Issue by renyuneyun** [eyereasoner/eye#113]
When using empty graphs with `--entail` and `--not-enail`, eye will always consider it false.

But, in principle, shouldn't at least `eye --quiet SOME_DOC.ttl --entail SOME_EMPTY_DOC.ttl` and `eye --quiet SOME_EMPTY_DOC.ttl --entail SOME_OTHER_EMPTY_DOC.ttl` be true?

**Comment by josd** [comment]
It indeed doesn't say `true` because it can't construct it and the good news is that `--not-entail` doesn't say `true`.
Will see what I can but for now it is first working hard on https://github.com/eyereasoner/lingua and then fixing eye where it is really broken.

**Comment by josd** [comment]
Should be working with `EYE v10.19.6 (2024-08-24)`

**Comment by renyuneyun** [comment]
Thanks very much! It works now.
