### ISSUE TITLE
issue with skolem IRI

### ISSUE THREAD

**Issue by giacomociti** [eyereasoner/eye#118]
until version 10.23.2, the following rules produced `skolem:bn_5 a :Success`.
```turtle
# eye --nope --quiet --pass-only-new repro.n3
@prefix : <http:/example.org/>.
@prefix skolem: <https://eyereasoner.github.io/.well-known/genid/d983461b-11b7-4e52-89c1-328e91bf1de1#>.

:s :value 1 .
:s :copy skolem:bn_5.

{ ?s :value ?value } => { ?s a :Success } .

{
    :s :copy ?o
}
=> 
{
    { ?o :value ?value } <= { :s :value ?value }
} .

```
Now (since v10.23.3) the reasoner hangs with 100% CPU consumption.
The issue is not present replacing the skolem IRI with a regular IRI.

**Comment by josd** [comment]
Thanks for your observation and it should be fixed in `v10.24.13`

**Comment by josd** [comment]
Yet another version so that https://github.com/eyereasoner/eye/blob/master/reasoning/bng/issue118.trig is now working.

**Comment by giacomociti** [comment]
thanks
