### ISSUE TITLE
jiti_list/0 is not a built-in predicate (missing use_module/1 or use_module/2 directive)

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#12]
https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L293

Add the following directive to make the dependency explicit and avoid depending on auto-loading:

```logtalk
:- use_module(library(prolog_jiti)).
```

**Comment by josd** [comment]
Thank you very much @pmoura and this issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1552
