### ISSUE TITLE
Avoid generating temporary atoms

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#13]
The following two `atom_concat/3` goals generate temporary atoms that are not used. This just pollutes the atom table and gives more work to the (computationally expensive) atom garbage collector:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L1690-L1691

Better rewrite the calls using `sub_atom/5`:

```logtalk
 (   sub_atom(C, 0, _, _, 'bn_') 
 ;   sub_atom(C, 0, _, _, 'e_')
```

**Comment by pmoura** [comment]
Same at:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L4039-L4040

**Comment by josd** [comment]
Thank you very much @pmoura and the issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1602
