### ISSUE TITLE
Redundant call/1 wrapper

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#14]
The following line:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L4479

can be simplified to:

```logtalk
catch(\+ F, _, true) 
```

On a side note, it's dangerous to capture and ignore **all** exceptions as you're doing here.

**Comment by pmoura** [comment]
Same at:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L11049

The whole clause can be simplified to:

```logtalk
mf(A) :-
    forall(
        catch(A, _, fail),
        format(user_error, '*** ~q~n', [A])
    ),
    flush_output(user_error).
```

**Comment by josd** [comment]
Thank you very much @pmoura and the issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1622
