### ISSUE TITLE
Redundant use of the =../2 predicate

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#15]
The following call:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L5253

can be simplified to:

```logtalk
Z = tuple(X, Y)
```

This avoids  creating a temporary list that will need to be garbage collected.

**Comment by josd** [comment]
Thank you very much @pmoura and the issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1628
