### ISSUE TITLE
Redundant calls to append/2

### ISSUE THREAD

**Issue by pmoura** [eyereasoner/eye#16]
All the calls to `append/2` in the following clauses are redundant:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L10867-L10890

You can write instead:

```logtalk
ncodes(A, B) :-
    number_codes(A, D),
    (   A < 10
    ->  B = [0'0| D]
    ;   B = D
    ).

ycodes(A, B) :-
    C is abs(A),
    number_codes(C, D),
    (   C < 10
    ->  E = [0'0, 0'0, 0'0| D]
    ;   (   C < 100
        ->  E = [0'0, 0'0| D]
        ;   (   C < 1000
            ->  E = [0'0| D]
            ;   E = D
            )
        )
    ),
    (   A >= 0
    ->  B = E
    ;   B = [0'-|E]
    ).
```

There may be others.

**Comment by pmoura** [comment]
There are also calls that can be optimized. For example, instead of:

https://github.com/josd/eye/blob/f453603d036b52257bad95bc4e61ce16667c4dd9/eye.pl#L10865

you can write:

```logtalk
append([C, [0'P| Days], [0'D, 0'T| Hours], [0'H| Minutes], [0'M| Seconds], [0'S]], B).
```

**Comment by josd** [comment]
Thank you very much @pmoura and the issue should be fixed in https://github.com/josd/eye/releases/tag/v21.0214.1641
