### ISSUE TITLE
Invalid document error with @false

### ISSUE THREAD

**Issue by logicReasoner** [eyereasoner/eye#17]
@josd  In https://github.com/josd/eye/blob/55b57949312cedbc517f4d02fa84ecffec5eee53/reasoning/skos/skos-rules.n3  there are rules that express disjoint relations, e.g.
`{ ?x skos:exactMatch ?y. ?x skos:broadMatch ?y } => @false.`
But when I try to use the same syntax in my files, I get an error: ` ** invalid_document(after_line(15))`
On the other hand,
`{ ?x skos:exactMatch ?y. ?x skos:broadMatch ?y } => false.` (without the `@` in front of `false`) seems to get accepted by EYE. Is the latter rule being interpreted the same way as when using `@false`?

**Comment by josd** [comment]
@logicReasoner thanks for observing and it is now corrected from `@false` to `false`.
Years ago we deprecated the keywords `@has`, `@is`, `@of`, `@true` and `@false` and since a while they are also not longer supported. One should use `has`, `is`, `of`, `true` and `false` instead.
