### ISSUE TITLE
Incorrect datatype for language strings

### ISSUE THREAD

**Issue by pchampin** [eyereasoner/eye#19]
According to [the spec](https://www.w3.org/TR/rdf11-concepts/#h3_section-Graph-Literal), literals with a language tag have the datatype `rdf:langString`. However, the following N3 code does not give the correct result in EYE
```
@prefix log: <http://www.w3.org/2000/10/swap/log#> .

{ (?lv ?dt) log:dtlit "a"@fr } => { :RESULT :is ?dt }.
```
Got: `:RESULT :is xsd:string.`
Expected `:RESULT :is rdf:langString.`

**Comment by josd** [comment]
Thank you very much Pierre-Antoine for the observation and it is now fixed in https://github.com/josd/eye/releases/tag/v21.0526.1011
