### ISSUE TITLE
How can I embed the EYE reasoning engine in a C++ application

### ISSUE THREAD

**Issue by logicReasoner** [eyereasoner/eye#2]
@josd,  First thanks for your hard work on this amazing project!
I've been playing with EYE for a while (solving some logic puzzles, etc.).
Now, I'd like to embed it directly into a C++ application. For the purpose passing millions of rules and data triples directly. 

I am thinking of something similar to using SWI Prolog from C++, e.g.
https://github.com/SWI-Prolog/packages-cpp/blob/master/likes.cpp

PS, I am aware of using docker to run EYE and also use the HTTP server client interface. But those add too much latency when dealing with huge amounts of data.
TIA!

**Comment by josd** [comment]
Thanks for the feedback and the exciting plans!
At this moment the interface to use EYE is like
swipl -x /opt/eye/lib/eye.pvm -- "$@"
or (but this is much slower)
swipl -f /opt/eye/src/eye.pl -g main -- "$@"
You can can get a huge performance increase for
loading millions of triples and rules when you
make a dedicated pvm file via e.g.
swipl -q -f /opt/eye/src/eye.pl -g main -- --nope your_static_large_files.n3 --image your_dedicated_eye.pvm
and then call swipl from C++ like
swipl -x your_dedicated_eye.pvm -- "$@" your_dynamic_files.n3 -- query your_query.n3
