### ISSUE TITLE
string:format vs. e:format builtin

### ISSUE THREAD

**Issue by rybesh** [eyereasoner/eye#21]
Based on my experimentation, it seems that eye does not implement the `string:format` builtin with (old-style) Python string formatting, but instead implements `e:format` with SWI Prolog `format/2` formatting. Is that correct? 

I don't mind using the latter rather than the former, but I'm just trying to make sure I understand correctly.

**Comment by josd** [comment]
Your understanding is correct. Once we make up consensus in https://w3c.github.io/N3/spec/ about the core built-ins we will implement them all and --restricted will be restricting the reasoner to core built-ins.

**Comment by rybesh** [comment]
Great, thank you.
