### ISSUE TITLE
Using e:becomes

### ISSUE THREAD

**Issue by rybesh** [eyereasoner/eye#22]
Is there a simple example someplace of how `e:becomes` is intended to work?

I had thought that it would be used like `log:implies` but that it would retract the subject graph in addition to adding the object graph. But I can’t seem to get that to work.

Here's the specific rule I am working on:

```ttl
{
    ?dtd time:unitType ?unit
    . ?unit time:years ?duration
    . ?duration e:numeral ?years
    . ?years log:equalTo 100
} => {
    ?dtd time:unitType time:unitCentury
} .
```

I'd like to change this to use `e:becomes` so that the triples in the subject are retracted; i.e. the conclusion replaces the antecedent.

(Also, please let me know if there is someplace else where you would prefer I ask questions like this.)

**Comment by josd** [comment]
No problem to ask it here :-)
There is an example of the use of e:becomes in https://github.com/josd/eye/blob/master/reasoning/gps/gps-plugin.n3
and you can test it in the directory eye/reasoning/gps via
```
$ eye --quiet --nope gps-plugin.n3 gps-example1.n3 --query gps-query1.n3 2>/dev/null
PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX list: <http://www.w3.org/2000/10/swap/list#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX gps: <http://josd.github.io/eye/reasoning/gps/gps-schema#>
PREFIX : <http://josd.github.io/eye/reasoning#>

:i1 gps:path ((:drive_gent_brugge :drive_brugge_oostende) 2400.0 0.01 0.9408 0.99).
:i1 gps:path ((:drive_gent_kortrijk :drive_kortrijk_brugge :drive_brugge_oostende) 4100.0 0.018000000000000002 0.903168 0.9801).
```
It is a built-in and it retracts the triples in the subject graph and asserts the triples in the object graph and it
is intented to implement linear logic implication.
See also https://scholar.google.be/citations?view_op=view_citation&hl=en&user=-vOppWIAAAAJ&sortby=pubdate&citation_for_view=-vOppWIAAAAJ:6_hjMsCP8ZoC

**Comment by rybesh** [comment]
Thank you. I can see that the GPS example uses `e:becomes`, but I have trouble understanding it because it also uses other builtins I'm not familiar with like `e:call` and `e:finalize`. I'm not sure if I also need these, or if they are only necessary for the GPS case. I wonder if you might post a minimal example that could help me see how I can use `e:becomes` for my case?

**Comment by josd** [comment]
A simple example is
```
$ cat eb.n3
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :PoisonDrinker.

{{?S a :PoisonDrinker} e:becomes {?S a :DeadPerson}} => {?S a ?B}.
```
which should give
```
$ eye --quiet --nope eb.n3 --pass 2>/dev/null
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :DeadPerson.
```
So `:Socrates a :PoisonDrinker` is retracted and `:Socrates a :DeadPerson` is asserted.

**Comment by josd** [comment]
Built-ins can not be retracted nor asserted hence can't be part of the subject or object of e:becomes.

**Comment by rybesh** [comment]
Thank you again! That is very helpful.

**Comment by rybesh** [comment]
Playing around with this example, I noticed something odd: if I use the `--pass-only-new` flag, the triples asserted in the object of `e:becomes` are not output:

```
$ eye --quiet --nope eb.n3 --pass-only-new 2>/dev/null
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>


```

Is this because `:Socrates a :DeadPerson` is “asserted” rather than “derived”? (It still seems like a “new” triple, though.)

**Comment by rybesh** [comment]
I’m also a bit confused by this behavior:

The following produces `:Socrates a :DeadPerson` as expected:
```ttl
PREFIX : <http://example.org/test#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

:Socrates a :PoisonDrinker .
:Socrates :drinksPoisonAmount "10"^^xsd:decimal .

{{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal } e:becomes {?S a :DeadPerson}} => {?S a ?B} .
```

But if the datatyped value is produced via the `log:dtlit` builtin:
```ttl
PREFIX : <http://example.org/test#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

:Socrates a :PoisonDrinker .

{ ("10" xsd:decimal) log:dtlit ?amount } => { :Socrates :drinksPoisonAmount ?amount } .

{{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal } e:becomes {?S a :DeadPerson}} => {?S a ?B} .
```

… then the result is:

```ttl
:Socrates a :PoisonDrinker.
:Socrates :drinksPoisonAmount "10"^^xsd:decimal.
```

Is this also a case of “built-ins cannot be retracted,” because the datatyped literal in the subject was created via a builtin?

**Comment by josd** [comment]
> Playing around with this example, I noticed something odd: if I use the `--pass-only-new` flag, the triples asserted in the object of `e:becomes` are not output:
> 
> ```
> $ eye --quiet --nope eb.n3 --pass-only-new 2>/dev/null
> PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
> PREFIX : <http://example.org/test#>
> ```
> 
> Is this because `:Socrates a :DeadPerson` is “asserted” rather than “derived”? (It still seems like a “new” triple, though.)

Thanks for the observation and this is now corrected in https://github.com/josd/eye/releases/tag/v21.0920.2018

> ...
>
> But if the datatyped value is produced via the `log:dtlit` builtin:
> 
> ```turtle
> PREFIX : <http://example.org/test#>
> PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
> PREFIX log: <http://www.w3.org/2000/10/swap/log#>
> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
> 
> :Socrates a :PoisonDrinker .
> 
> { ("10" xsd:decimal) log:dtlit ?amount } => { :Socrates :drinksPoisonAmount ?amount } .
> 
> {{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal } e:becomes {?S a :DeadPerson}} => {?S a ?B} .
> ```
> 
> … then the result is:
> 
> ```turtle
> :Socrates a :PoisonDrinker.
> :Socrates :drinksPoisonAmount "10"^^xsd:decimal.
> ```
> 
> Is this also a case of “built-ins cannot be retracted,” because the datatyped literal in the subject was created via a builtin?

It is actually retracted but a bit later again asserted by the rule
```
{ ("10" xsd:decimal) log:dtlit ?amount } => { :Socrates :drinksPoisonAmount ?amount } .
```
which is the intrinsic behaviour of the eye forward chaining (rules are repeatedly running as long as new conclusions follow).

**Comment by rybesh** [comment]
> It is actually retracted but a bit later again asserted

I understand why `:Socrates :drinksPoisonAmount "10"^^xsd:decimal` is in the conclusion; what I don’t understand is why `:Socrates a :PoisonDrinker` is in the conclusion (rather than `:Socrates a :DeadPerson`).

**Comment by rybesh** [comment]
> Thanks for the observation and this is now corrected in https://github.com/josd/eye/releases/tag/v21.0920.2018

Thanks! Using the latest version,  providing 
```ttl
:Socrates a :PoisonDrinker.
{{?S a :PoisonDrinker} e:becomes {?S a :DeadPerson}} => {?S a ?B}.
```
with `--pass-only-new` indeed gives me `:Socrates a :DeadPerson`.

But if I change it to:
```ttl
:Socrates :drinks :poison.
{?S :drinks :poison} => {?S a :PoisonDrinker}.
{{?S :drinks :poison ; a :PoisonDrinker } e:becomes {?S a :DeadPerson}} => {?S a ?B}.
```
then with `--pass` I get only `:Socrates a :DeadPerson` (as expected), but with `--pass-only-new` I get
```ttl
:Socrates a :PoisonDrinker.
:Socrates a :DeadPerson.
```

Is this intended? `:Socrates a :PoisonDrinker` was derived but then retracted, so should it be “new”?

(For context, I am trying to determine the best way to produce a file containing only derived triples but no retracted ones. Maybe I should just use `--pass` and then post-process with SPARQL to remove the non-derived (i.e. input) triples?)

**Comment by josd** [comment]
> > It is actually retracted but a bit later again asserted
> 
> I understand why `:Socrates :drinksPoisonAmount "10"^^xsd:decimal` is in the conclusion; what I don’t understand is why `:Socrates a :PoisonDrinker` is in the conclusion (rather than `:Socrates a :DeadPerson`).

Right, this is due to the fact that the parser is a bit too confident to parse `"10"^^xsd:decimal` into integer `10` instead of the internal term `literal('10',type('<http://www.w3.org/2001/XMLSchema#decimal>'))`
This is now fixed in https://github.com/josd/eye/releases/tag/v21.0920.2142 and with `--pass` you should now get
```
:Socrates a :DeadPerson.
:Socrates :drinksPoisonAmount "10"^^xsd:decimal.
```

**Comment by josd** [comment]
> ...
> then with `--pass` I get only `:Socrates a :DeadPerson` (as expected), but with `--pass-only-new` I get
> 
> ```turtle
> :Socrates a :PoisonDrinker.
> :Socrates a :DeadPerson.
> ```
> 
> Is this intended? `:Socrates a :PoisonDrinker` was derived but then retracted, so should it be “new”?

As we said before, it is indeed retracted but asserted again and the `--pass-only-new` is rather primitive in that it outputs each time something is asserted - it is actually more something like a debugging thing ;-)

> (For context, I am trying to determine the best way to produce a file containing only derived triples but no retracted ones. Maybe I should just use `--pass` and then post-process with SPARQL to remove the non-derived (i.e. input) triples?)

Maybe that is indeed better.

**Comment by rybesh** [comment]
>  `--pass-only-new` is rather primitive in that it outputs each time something is asserted

OK, that’s what I figured—so I will find another solution.

Thanks for your quick replies and fixes, I really appreciate it!

**Comment by josd** [comment]
With the latest eye https://github.com/josd/eye/releases/tag/v21.0921.1204 `--pass-only-new` should now produce _only new_ triples:
```
$ cat eb3.n3
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

{{?S :drinks :poison ; a :PoisonDrinker } e:becomes {?S a :DeadPerson}} => {?S a ?B}.
{?S :drinks :poison} => {?S a :PoisonDrinker}.
:Socrates :drinks :poison.
```

```
$ eye --nope eb3.n3 --pass-only-new
eye --nope eb3.n3 --pass-only-new
EYE v21.0921.1204 josd
SWI-Prolog version 8.3.29-32-ga624386fa
starting 32 [msec cputime] 29 [msec walltime]
#Processed by EYE v21.0921.1204 josd
#eye --nope eb3.n3 --pass-only-new

GET file:///tmp/eb3.n3 SC=3
networking 1 [msec cputime] 1 [msec walltime]
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :DeadPerson.

reasoning 1 [msec cputime] 0 [msec walltime]
#2021-09-21T12:12:04.711Z in=3 out=1 ent=1 step=2 brake=2 inf=18175 sec=0.034 inf/sec=534559
#ENDS

2021-09-21T12:12:04.711Z in=3 out=1 ent=1 step=2 brake=2 inf=18175 sec=0.034 inf/sec=534559
```

**Comment by josd** [comment]
The fact that rules continuously fire till nothing new is produced anymore can be annoying like in your previous example
```
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :PoisonDrinker.
{("10" xsd:decimal) log:dtlit ?amount} => {:Socrates :drinksPoisonAmount ?amount}.
{{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal} e:becomes {?S a :DeadPerson}} => {?S a ?B}.
```
which reproduces `:Socrates :drinksPoisonAmount "10"^^xsd:decimal.` via rule `{("10" xsd:decimal) log:dtlit ?amount} => {:Socrates :drinksPoisonAmount ?amount}.`
This can be easily avoided by having an explicit additional condition in the premise namely `{:Socrates a :PoisonDrinker. ("10" xsd:decimal) log:dtlit ?amount} => {:Socrates :drinksPoisonAmount ?amount}.`

So for
```
$ cat eb2.n3
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :PoisonDrinker.
{:Socrates a :PoisonDrinker. ("10" xsd:decimal) log:dtlit ?amount} => {:Socrates :drinksPoisonAmount ?amount}.
{{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal} e:becomes {?S a :DeadPerson}} => {?S a ?B}.
```
we now get
```
$ eye --quiet --nope eb2.n3 --pass-only-new 2>/dev/null
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>
PREFIX : <http://example.org/test#>

:Socrates a :DeadPerson.
```

**Comment by rybesh** [comment]
Thanks, that makes sense.

I was looking at your paper “Predicting future state for adaptive clinical pathway management” and it seems very useful to be able to clearly separate 1) conditions for applying a transition rule, 2) statements to be retracted, and 3) statements to be asserted. I think part of the conceptual difficulty I was having with using `e:becomes` was confusion between 1) and 2).

Another thing that still confuses me:

Rules using `e:becomes` take the form `{?X e:becomes ?Y} => ?Z`. `?X` is the graph of statements to be retracted and `?Y` is the graph of statements to be asserted. But then what is `?Z`?

**Comment by josd** [comment]
Thanks for the nice 1)2)3) summary.

`e:becomes` is a built-in and buit-ins can only be used in the premis of a rule, so we need a rule and the conclusion `?Z` is nothing specific and was just for demonstration purposes.

So you can also write a rule like
`{{?S a :PoisonDrinker ; :drinksPoisonAmount "10"^^xsd:decimal} e:becomes {?S a :DeadPerson}} => {}.`
or
`{{?S :drinks :poison ; a :PoisonDrinker } e:becomes {?S a :DeadPerson}} => {{?S :drinks :poison ; a :PoisonDrinker } :became {?S a :DeadPerson}}.`

**Comment by rybesh** [comment]
OK, I see. I tried changing `?Z` to different things and it didn’t seem to have any effect, so it’s good to understand why. Thanks again!

**Comment by josd** [comment]
So your 1) conditions for applying a transition rule, 2) statements to be retracted, and 3) statements to be asserted all occur in the premis of rules like
`{Condition-triples. {From-triples} e:becomes {To-triples}} => {Conclusion-triples}.`

**Comment by josd** [comment]
> OK, I see. I tried changing `?Z` to different things and it didn’t seem to have any effect, so it’s good to understand why. Thanks again!

Well, technically speaking, the ?Z is concluded and it will be asserted when it is not yet known.
So in the original example `?S a ?B` will be concluded as `:Socrates a _:sk_0` which means `Socrates is something` but that is already known as `:Socrates a :DeadPerson`

With a rule like `{{?S :drinks :poison ; a :PoisonDrinker } e:becomes {?S a :DeadPerson}} => {{?S :drinks :poison ; a :PoisonDrinker } :became {?S a :DeadPerson}}.` you will see an additional triple concluded
```
:Socrates a :DeadPerson.
{:Socrates :drinks :poison. :Socrates a :PoisonDrinker} :became {:Socrates a :DeadPerson}.
```

**Comment by rybesh** [comment]
> the ?Z is concluded and it will be asserted when it is not yet known

Ah, I see. I guess in all the examples I tried it was already known, and so it just seemed to have no effect.
