### ISSUE TITLE
"non_rdf_entailment" error

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#27]
I tested —entail option like this:

In  ./test-entail.n3 , I write:
```
PREFIX : <http://www.example.com/>
:biggerThan :inverseOf :smallerThan.
{?p1 :inverseOf ?p2. ?a ?p1 ?b} => {?b ?p2 ?a}.
```

In ./test-entail-claim.n3:
```
PREFIX : <http://www.example.com/>
{?a :biggerThan ?b} => {?b :smallerThan ?a}.
```

And run 
`Eye —-nope ./test-entail.n3 --entail ./test-entail-claim.n3`

Gives me error message like this:
** ERROR ** file://.../test-entail-result.n3 ** non_rdf_entailment('<file://.../test-entail-claim.n3#in>'(_a,_b),after_line(2))

What does “non_rdf_entailment” mean?  And I want to know is it possible that the claim of entail is a rule?

**Comment by josd** [comment]
Thanks for asking and as you can see with `eye --help`
```
<query>
    --entail <rdf-graph>            output true if RDF graph is entailed
```
it checks `N3-rules-and-triples |- RDF-triples` and the reasoner is not capable to go beyond that
and thows a `non_rdf_entailment` exception.

**Comment by blackwint3r** [comment]
It seems like I made a rookie mistake... Thank you.
