### ISSUE TITLE
error of recursive backward rule

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#29]
`{{:x :y :z} <= {:a :b :c}} <= {:d :e :f}.
`
The simple one line code above give me error:
`** ERROR ** gre ** error(permission_error(modify,static_procedure,(:-)/2),context(system:assertz/1,_5794))
`
Or maybe this test case could be more simplified:
`{:x <= :y} <= :z. #same error
`

**Comment by josd** [comment]
This is indeed one of the limitations of backward rules.
Other limitations are that their conclusion can't be `false` or a `conjunction`

**Comment by blackwint3r** [comment]
Thank you.
by the way, what I want to do is like this:
```
{?x => ?y} <= {?SCOPE e:call ?y}. 
{?y <= ?x} <= {?SCOPE e:call ?y}.  #error above
{?x => ?y} <= {?SCOPE e:fail ?x. ?SCOPE e:fail ?y }. 
{?y <= ?x} <= {?SCOPE e:fail ?x. ?SCOPE e:fail ?y}.   #error above
```
Which mimic the behavior of [material implication](https://en.wikipedia.org/wiki/Material_conditional), add some additional semantics to log:imply and "<=", so I can place them inside the premise of other rules, in a recursive style.
But now I have found a better way to do this ...

Anyway thanks !
