### ISSUE TITLE
Missing inference involving hasValue restriction and domain

### ISSUE THREAD

**Issue by pchampin** [eyereasoner/eye#3]
I have the following N3 file
```
:hasSpine rdfs:domain :Animal.
:Chordate rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty :hasSpine ;
    owl:hasValue true;
].
```
which I use together with all OWL-related files (`eye/reasoning/rpo/[ro]*.n3`).
I was expecting EYE to infer the following triple:
```
:Chordate rdfs:subClassOf :Animal.
```
but it didn't. Protégé (with Hermit) did, on the other hand.

I solved it with the following axiom:
```
{ ?c rdfs:subClassOf [ owl:onProperty [ rdfs:domain ?d ]; owl:hasValue [] ] }
=>
{ ?c rdfs:subClassOf ?d }.
```

I think this axiom should be added (as well as related axioms for `owl:someValuesFrom`, `owl:minCardinality` (>0) and `owl:exactCardinality` (>0)) to the relevant files in `reasoning/rpo/`.

**Comment by josd** [comment]
The rules in eye/reasoning/rpo are more or less to conform with OWL 2 RL i.e.
https://www.w3.org/TR/owl2-profiles/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules
I would be glad to add your axiom to https://github.com/josd/eye/blob/master/reasoning/rpo/owl-hasValue.n3
but I am not 100% sure that it is correct.
@doerthe could you confirm that @pchampin 's axiom is correct?

**Comment by doerthe** [comment]
Sorry for my late answer, I did not see your question. 

The rule of Pierre-Antoine looks fine to me. 
I would however not add them directly to your rules, Jos, since you cover a well-known fragment of OWL-DL which is OWL-RL. By adding rules directly, it is rather difficult to predict the behavior of the reasoning process. So, maybe mark your original set explicitely as OWL-RL and then add extensions.

Since this is a topic I like a lot and I also played with, maybe it would make sense to collect all the rules we write as extensions of OWL-RL in a joint repository. We could exchange and use them and also report problems to each other. Should I create a folder for that on the N3 git or should we do it here in Jos' repository (with his permission of course)?

**Comment by josd** [comment]
OK that is nice and now the rule is available at https://github.com/josd/eye/blob/master/reasoning/rpo/owl-hasValue-ext.n3
Of course, feel free to make changes to EYE repository :-)

**Comment by pchampin** [comment]
@doerthe 
Nitpicking a little: I am assuming that the rules provided with EYE are drawn from [§4.3 of OWL2 Profiles](https://www.w3.org/TR/2012/REC-owl2-profiles-20121211/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules), in which case they actually cover **OWL 2 RL/RDF**, which I understand to be a *subset* of OWL-RL (it is presented as “the *basis* for such an implementation”). More precisely, since OWL-RL allows the use of `hasValue`, I consider that the inference added my rule should be part of a complete OWL-RL implementation.

That being said, and nitpicking apart, I totally agree with you that we should favour *well identified* sets of rules. And OWL-RL/RDF is exactly that. Extending this set arbitrarily would only muddy the water (unless we can prove that we have reached OWL-RL exacttly -- but I am assuming this might be an open problem).

@josd 
Following Doerthe's recommendation to keep "additional" rules separate from the well identified set you originally provided:
I suggest renaming the new file to `ext-owl-hasValue.n3` or `x-owl-hasValue.n3`. This makes it easier to select only the "standard" subset of rules (`rpo/[or]*.n3`) or the "extended" subset of rules (`rpo/[orx]*.n3`).

**Comment by josd** [comment]
@pchampin this is indeed a much better naming convention and the file is now renamed to
https://github.com/josd/eye/blob/master/reasoning/rpo/x-owl-hasValue.n3
and for machines it is also available at
https://raw.githubusercontent.com/josd/eye/master/reasoning/rpo/x-owl-hasValue.n3

Your rule also reminds me at the time we made more such rules at
http://eulersharp.sourceforge.net/2003/03swap/owl-rules.n3 just to test owl.
