### ISSUE TITLE
strange behavior of backward rule

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#30]
I’m confused by the behavior of backward rule.
this example:

```
:Alice :type :human.
{?x :type :animal} <= {?x :type :human}. 
{?x :type :animal} => {?x :type :animal}. # not fired
{?x :type :animal} => {?x :type2 :animal}. # fired.
```

Give me result:
`:Alice :type2 :animal`

not what I expected : 
```
:Alice :type :animal
:Alice :type2 :animal
```

Why did the third rule fired while the second one did not ?

**Comment by josd** [comment]
This is indeed what EYE currently does.
The conclusion of a backward rule is never asserted as it could be non ground. 
The conclusion of a forward rule is asserted when it fails and the premis succeeds.

**Comment by blackwint3r** [comment]
Because the conclusion of second rule is succeeds already so it would not assert again. Thank you ! I got it.
But this is a bit counterintuitive, since by `{?x :type :animal} => {?x :type :animal}`, I told EYE make the conclusion **not only** succeed **but also** asserted ...

**Comment by josd** [comment]
A query would do what you want
```
$ cat example.n3
PREFIX : <http://example.org/test#>

:Alice :type :human.
{?x :type :animal} <= {?x :type :human}.

$ cat query.n3
PREFIX : <http://example.org/test#>

{?x :type :animal} => {?x :type :animal}.
{?x :type :animal} => {?x :type2 :animal}.

$ eye --quiet --nope example.n3 --query query.n3 2>/dev/null
PREFIX : <http://example.org/test#>

:Alice :type :animal.
:Alice :type2 :animal.
```
This is because query rules don't assert their conclusions but give them as answers.

**Comment by blackwint3r** [comment]
Thank you!
