### ISSUE TITLE
How to use log:Includes to find a triple not in the graph

### ISSUE THREAD

**Issue by phochste** [eyereasoner/eye#33]
In EYE v21.0811.1752 I used these N3 rules to find subject identifiers that are not an object in the data:

```
PREFIX ex:   <https://www.example.org/>
PREFIX log:  <http://www.w3.org/2000/10/swap/log#>

ex:MainSubject a ex:Tweet;
    ex:message "EYE rules" .

ex:Tweet a ex:Conversation.

{
    ?id a ?class .

    ?SCOPE log:notIncludes { ?subject ?predicate ?id } .
}
=>
{
    [ ex:TopGraph ?id ].
}.
```

which gave as result (only new):

```
_:sk_2 ex:TopGraph ex:MainSubject.
```

In version EYE v22.0128.1551 the result is empty. I understand how log:notIncludes is interpreted changed a bit. 
Is there a way to create an equivalent rule in the latest version of EYE?

**Comment by josd** [comment]
Thanks @phochste, will look into this asap but first have to bike to Ghent to have a meeting with @RubenVerborgh ;-)

**Comment by josd** [comment]
@phochste the latest version https://github.com/josd/eye/releases/tag/v22.0203.1955 gives again
```
PREFIX ex: <https://www.example.org/>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>

_:sk_2 ex:TopGraph ex:MainSubject.
```

**Comment by phochste** [comment]
Thx! I just noticed this in my inbox. It works!
