### ISSUE TITLE
Backward rule with blank node in its conclusion seems work incorrectly.

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#35]
Here is an example.  I want to express "For every person, there is one thing that is his/her mother", but it turn out anything could be any person's mother.

```
@prefix : <#>.
{?x :mother _:y} <= {?x a :person}. 
:Alice a :person.
{:Alice :mother :Alice} => {:got :weird :result1}.
{:Alice :mother :Bob} => {:got :weird :result2}.
```
gives me 
```
:got :weird :result1.
:got :weird :result2.
```

The forward rule version works correctly.

**Comment by josd** [comment]
Thanks for the observation and it should be fixed in https://github.com/josd/eye/releases/tag/v22.0219.2334
So no more :weird :results 😉

**Comment by blackwint3r** [comment]
great😄
