### ISSUE TITLE
Installation Instructions [Linux Debian]

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye#37]
I wanted to run some of my own tests on the eye reasoner on my machine.

I was trying to run the `./install.sh` script - but haven't got the `swipl` command installed. Is there a recommended place to install this from since it doesn't appear to be available from the `apt` package manager.

System Details:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I'm happy to PR a set of Linux installation instructions once I am able to get this working on my machine.

**Comment by josd** [comment]
You could install swipl as per https://www.swi-prolog.org/build/PPA.html

Another way to run eye locally is via https://hub.docker.com/r/bdevloed/eye/
