### ISSUE TITLE
How to access/use http:resp [ http:body ] . json as Literal(s)???

### ISSUE THREAD

**Issue by tduval-unifylogic** [eyereasoner/eye#38]
Hey Jos!

I'm taking the next step with n3patch where i'm calling out to a web service as a function (to extend the built-ins where necessary).  
Whereas we were setting literals _with literals_ in #36, I would like to use properties from the response body as the ```patch```. 

How do I go about this in the formula/rule? I have reviewed the [respath](https://github.com/josd/eye/blob/master/reasoning/restpath/path-9-3.n3) rule, but don't see where/how I can access response bodies (json) property values to use as literals?

Here is an example I have worked up.  The json that will be returned from the `[GET]` is as follows

```
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```
Here is the rule I have been attempting:

```
@prefix http: <http://www.w3.org/2011/http#>.
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix ex: <http://www.example.org/terms#>.

{ 
    ?person ex:givenName "Claudia" .
} 
=> 
{ 
    _:request http:methodName "GET" ;
        http:requestURI <https://jsonplaceholder.typicode.com/todos/1> ;
        http:resp [ http:body ?body ] .     
    ?person ex:givenName ?body .  # <<------ set with data from the response, e.g., ?body.title (illustrative)
} .
```

Is this a closed world limitation? I remember recently seeing some dialog where the reasoner keeps its scope only to the local environment. 

Thanks for your help!!

**Comment by josd** [comment]
Please have a look at https://restdesc.org/ and for instance https://ruben.verborgh.org/publications/verborgh_mtap_2013/
RESTdesc is using a reasoner to determine whether a service satisfies at set of conditions or even more advanced
reasoning is possible to decide on service matching, and to create complex compositions of different services.
The reasoner is not calling those services.

**Comment by tduval-unifylogic** [comment]
@josd 

AH! I TOTALLY GET IT!! THANKS!!! 

Is like OpenAPI spec, just N3!!! With pre and post-conditions!
