### ISSUE TITLE
list:remove keeps the member

### ISSUE THREAD

**Issue by phochste** [eyereasoner/eye#45]
In eye `v22.0827.1120` I tried:

```
@prefix : <urn:example:> .
{ (("a" "b" "c") "c") list:remove ("a" "b") } => { :test1 a :SUCCESS } .
{ (("a" "b" "c") "c") list:remove ("a" "b" "c") } => { :test2 a :FAILURE } .
```

and got as result 

```
<urn:example:test2> a <urn:example:FAILURE>.
```

**Comment by josd** [comment]
Thanks @phochste, it should be fixed in https://github.com/josd/eye/releases/tag/v22.0828.0945 and you should now get
```
<urn:example:test1> a <urn:example:SUCCESS>.
```

**Comment by phochste** [comment]
Super!

**Comment by josd** [comment]
It was implemented as `(list1 list2) list:remove list3` such that list3 is list1 with all elements of list2 removed

**Comment by phochste** [comment]
I'm trying to learn the built-ins by implementing for each one a small [example](https://github.com/phochste/Notation3-By-Exampe). For `list:remove` I got a bit confused by the definition in https://w3c.github.io/N3/files/builtin_spec.html and the eye and jen3 implementation.
