### ISSUE TITLE
Using n-quads

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye#58]
Merry Christmas - please respond to this *after* your break! I am now signing off for the evening anyway

---

In order to do the Sochrates query using RDF/JS quads in the eye-js package; I first want to convert to n-quads (it is the easiest thing to write using n3.js); which means my data looks like

```ttl
<http://example.org/socrates#Socrates> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/socrates#Human> .
    <http://example.org/socrates#Human> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://example.org/socrates#Mortal> .
    ?A <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?B _:b1 .
    ?S <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?A _:b1 .
    ?S <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?B _:b2 .
    _:b1 <http://www.w3.org/2000/10/swap/log#implies> _:b2 .
```

and my query looks like

```ttl
<http://example.org/socrates#Socrates> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?WHAT _:b1 .
<http://example.org/socrates#Socrates> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?WHAT _:b2 .
_:b1 <http://www.w3.org/2000/10/swap/log#implies> _:b2 .
```

When I try and run this in a query I get a syntax error on the last line of each file/ Is there an easy way of resolving this?

**Comment by josd** [comment]
That is normal :-)
The business of eye is reasoning and not understanding and speaking different languages but understanding and speaking one lingua franca which is N3.

Also a Merry Christmas Jesse!
