### ISSUE TITLE
How to express `OR` and negation?

### ISSUE THREAD

**Issue by logicReasoner** [eyereasoner/eye#6]
I have a few questions:
1) How do I express logical `or` do I have to use `,` or `;`?
Example:
if a box is big and it is either green or blue or red, then it's a new box:
```{?X a :Box. ?X a :big. (?X a :green OR ?X a :blue OR ?X a :red)} => {?X a :newBox}.```

2) How do I use negation of a predicate, e.g.
if a box is big and it is NOT green, then it's a blue box:
```{?X a :Box. ?X a :big. not(?X a :green)} => {?X a :blueBox}.```

3) How do I properly use a recursive predicate, e.g. if we have:
``` {?P a :relType1. ?X ?P ?Y. ?Y ?P ?Z.} => {?X ?P ?Z}.
:someRel a :relType1.
:A1 :someRel :A2.
:A2 :someRel :A3.
:A4 :someRel :A5.
```
When I query for ```{:A1 :someRel :A3.} => {:A1 :someRel :A3.}.```, then it finds a solution, but 
it does NOT for the following two:
```
{:A1 :someRel :A4.} => {:A1 :someRel :A4.}.
{:A1 :someRel :A5.} => {:A1 :someRel :A5.}. 
``` 

4) Does EYE automatically check for consistency (integrity) in the DB of facts while adding each new fact.

5) How to `\=`, i.e. the opposite of `=`. I noticed `log:notEqualTo` and `owl:differentFrom` but they don't seem to have the same power as `=`, i.e. those never trigger any `eam` inference errors.

Sorry for the long question and thanks in advance @josd  ! :)

**Comment by josd** [comment]
1/ EYE is using N3 syntax and there is no OR operator but you can express your rule as follows
```
{?X a :Box. ?X a :big. ?X a :green} => {?X a :newBox}.
{?X a :Box. ?X a :big. ?X a :blue} => {?X a :newBox}.
{?X a :Box. ?X a :big. ?X a :red} => {?X a :newBox}.
```

2/ There is also no NOT operator but you can use "scoped negation as failure" (SNAF) which is offered by specific built-ins and the N3 community group currently has a pending issue https://github.com/w3c/N3/issues/18 so for EYE you can express your rule as follows:
`{?X a :Box. ?X a :big. ?SCOPE e:fail {?X a :green}} => {?X a :blueBox}.`

3/ It is not clear what you mean with "query for `{:A1 :someRel :A3.} => {:A1 :someRel :A3.}.`"?
As a rule used in the --query uri, which basically means QUERY => ANSWER and ANSWER is *not* added to the deductive closure, no answer is found. Could you clarify what is your input, your query and your answer?
When you add a recursive rule to your input
```
@prefix : <http://example.org/test#>.

:someRel a :relType1.
:A1 :someRel :A2.
:A2 :someRel :A3.
:A4 :someRel :A5.

{?A :someRel ?B. ?B :someRel ?C} => {?A :someRel ?C}.
```
and for query
```
@prefix : <http://example.org/test#>.

{?A :someRel ?B} => {?A :someRel ?B}.
```
`eye --nope the_above_input --query the_above_query` gives
```
@prefix : <http://example.org/test#>.

:A1 :someRel :A2.
:A2 :someRel :A3.
:A4 :someRel :A5.
:A1 :someRel :A3.
```
If you add `:A3 :someRel :A4.` to your input the answers are
```
:A1 :someRel :A2.
:A2 :someRel :A3.
:A3 :someRel :A4.
:A4 :someRel :A5.
:A1 :someRel :A3.
:A2 :someRel :A4.
:A3 :someRel :A5.
:A1 :someRel :A4.
:A2 :someRel :A5.
:A1 :someRel :A5.
```

4/ Yes, EYE is checking integrity constraints when the deductive closure grows, for instance for your modified ruleset
```
@prefix : <http://example.org/test#>.

{?P a :relType1. ?X ?P ?Y. ?Y ?P ?Z.} => {?X ?P ?Z}.
{?P a :relType2. ?X ?P ?Y. ?Y ?P ?X.} => false.
{?P a :relType2. ?X ?P ?Y.} => {?Y ?P ?X}.

:someRel a :relType1.
:A1 :someRel :A2.
:A2 :someRel :A3.
:A4 :someRel :A5.

:someRel2 a :relType2.
:A1 :someRel2 :A2.
:A2 :someRel2 :A3.
```
the inference fuse is blown
```
$ eye --nope ~/temp/ifuse.n3 --pass
...
GET file:///home/jdroo/temp/ifuse.n3 SC=10
networking 0 [msec cputime] 14 [msec walltime]
** ERROR ** eam ** inference_fuse({:someRel2 a :relType2. :A1 :someRel2 :A2. :A2 :someRel2 :A1} => false)
```

**Comment by logicReasoner** [comment]
Thanks for your answers!
1) how difficult would it be to implement a new built-in in the EYE parser so that either `;` or `,`  is interpreted as logical `OR`? I don't mean to add it in the master branch since it's not compatible with N3 but rather separately in a non-official branch?

2) `?SCOPE e:fail ` is a clever hack. I'll give it a shot.

3) Yes, I noticed my mistake: I was missing ```:A3 :someRel :A4.``` . Thanks!

4) Yes, exactly what I needed.

5) What should I use as `\=` (a comparison without unification), i.e. the opposite of `=`. I noticed `log:notEqualTo` and `owl:differentFrom` but they don't  seem to do anything out of the box. I guess that I need some built-in which is the inverse of `=`? I tried to implement my own `:notEqualTo` using the `?SCOPE e:fail ` trick but I could not make it work with the same power as `=`.

**Comment by josd** [comment]
Thanks for the questions!

1/ Instead of yet another built-in we have [e:derive](https://github.com/josd/eye/blob/master/log-rules.n3#L169) that can be used here:
```
@prefix e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>.
@prefix : <http://example.org/test#>.

:unit1 a :Box, :big, :blue.

{?X a :Box. ?X a :big. (";" {?X a :green} {(";" {?X a :blue} {?X a :red}) e:derive true}) e:derive true} => {?X a :newBox}.
```
and `eye --nope the_above_input --pass` gives
```
:unit1 a :Box.
:unit1 a :big.
:unit1 a :blue.
:unit1 a :newBox.
```

5/ `log:notEqualTo` is a built-in that is the inverse of `log:equalTo` which is unifying subject and object. As explained in 1/ you could also try with `("=" ?S ?O) e:derive false`

**Comment by logicReasoner** [comment]
Hello again @josd  with some additional questions that don't deserve a separate issue :)

I am playing around with `EYE` and trying to solve some (slightly modified) Lewis Carol puzzles, e.g. 
```
(1) No potatoes of mine, that are new, have been boiled;
(2) All my potatoes that are unfit to eat, are in this dish ;
(3) No unboiled potatoes of mine are fit to eat.
-------------------
Q: are there any new potatoes in this dish?
```
This is my solution so far:
```
@prefix : <file:///#>.
@prefix e: <file:///e#>.


#:potato1 a :newPotato.

{?X a :newPotato} => {?SCOPE e:fail {?X a :boiled}}.
{?SCOPE e:fail {?X a :fitToEat}} => {?X a :potatoInDish}.
{?SCOPE e:fail {?X a :boiled}} => {?SCOPE e:fail {?X a :fitToEat}}.
```
And in a separate query file:
```
{?X a :newPotato. ?X a :potatoInDish.} => {?X a :potatoInDish}.
```
-------------------------------
Q1) It seems to work if I uncomment the assertion `:potato1 a :newPotato.` but adding that assertion seems a bit like a hack. It is something not mentioned in the puzzle. Is there a more general way of specifying "There exist some new potatoes." or "there exists at least one new potato, but I won't name it here explicitly"?
--------------------------------

Q2) How do I specify that `potato2` is NOT a new potato. I tried with:
```
{?SCOPE e:fail {:potato2 a :newPotato}}.
```
But I think that the above declaration got ignored by EYE.

--------------------------------
Q 3) (Somewhat related to Q1). We have the following puzzle:
```
'Some animals are venomous. All venomous animals are dangerous to touch.'
Which of the following are valid deductions?
All non-venomous animals are safe (not dangerous) to touch.
Some animals are dangerous to touch.
Some animals are safe (not dangerous) to touch.
```
The second assertion can be specified as:
```
{?X a :venomous} => {?X a :dangerousToTouch}.
```
But I find a difficulty modeling the first assertion and the last two questions in EYE. Namely, I don't know how to specify the `some` quantifier (`Some X are Y`). Any suggestions?
--------------------------------
Question 4)  Some unrelated question. Is the use of `<=` in the following file just for readability or does it mean something different than the left and right hand side have changed places for readability
https://github.com/josd/eye/blob/master/reasoning/4color/4color_rules.n3
