### ISSUE TITLE
How to express quantifiers like `Some X are Y`

### ISSUE THREAD

**Issue by logicReasoner** [eyereasoner/eye#7]
I am playing around with `EYE` and trying to solve some puzzles, e.g. 
```
(1) No potatoes of mine, that are new, have been boiled;
(2) All my potatoes that are unfit to eat, are in this dish ;
(3) No unboiled potatoes of mine are fit to eat.
-------------------
Q: are there any new potatoes in this dish?
```
This is my solution so far:
```
@prefix : <file:///#>.
@prefix e: <file:///e#>.


#:potato1 a :newPotato.

{?X a :newPotato} => {?SCOPE e:fail {?X a :boiled}}.
{?SCOPE e:fail {?X a :fitToEat}} => {?X a :potatoInDish}.
{?SCOPE e:fail {?X a :boiled}} => {?SCOPE e:fail {?X a :fitToEat}}.
```
And in a separate query file:
```
{?X a :newPotato. ?X a :potatoInDish.} => {?X a :potatoInDish}.
```
-------------------------------
Q1) It seems to work if I uncomment the assertion `:potato1 a :newPotato.` but adding that assertion seems a bit like a hack. It is something not mentioned in the puzzle. Is there a more general way of specifying "There exist some new potatoes." or "there exists at least one new potato, but I won't name it here explicitly"?
--------------------------------

Q2) How do I specify that `potato2` is NOT a new potato. I tried with:
```
{?SCOPE e:fail {:potato2 a :newPotato}}.
```
But I think that the above declaration got ignored by EYE.

--------------------------------
Q 3) (Somewhat related to Q1). We have the following puzzle:
```
'Some animals are venomous. All venomous animals are dangerous to touch.'
Which of the following are valid deductions?
All non-venomous animals are safe (not dangerous) to touch.
Some animals are dangerous to touch.
Some animals are safe (not dangerous) to touch.
```
The second assertion can be specified as:
```
{?X a :venomous} => {?X a :dangerousToTouch}.
```
But I find a difficulty modeling the first assertion and the last two questions in EYE. Namely, I don't know how to specify the `some` quantifier (`Some X are Y`). Any suggestions?
--------------------------------
Question 4)  Some unrelated question. Is the use of `<=` in the following file just for readability or does it mean something different than the left and right hand side have changed places for readability
https://github.com/josd/eye/blob/master/reasoning/4color/4color_rules.n3

**Comment by josd** [comment]
In N3 you can use `@forAll` and `@forSome` as explained in https://www.w3.org/TeamSubmission/n3/#Quantifica
In N3 there is no negation and so this limits your expressivity.
There as a few possibilities with negation verbs and what is called "scoped negation as failure" implemented via
built-ins such as log:notIncludes, e:findall and e:fail.
Also remark that the e: namespace is `@prefix e: <http://eulersharp.sourceforge.net/2003/03swap/log-rules#>.` 
and not `@prefix e: <file:///e#>.`

What I propose is that you raise concrete *implementation* issues and at least check those with another reasoner
such as https://www.w3.org/2000/10/swap/doc/cwm

**Comment by josd** [comment]
Logically speaking `P => C` and `C <= P` are the same but EYE uses the two different notations to control the chaining:

> Controlled chaining is backward chaining for rules using <= in N3
> and forward chaining for rules using => in N3.

**Comment by logicReasoner** [comment]
@josd thanks for your pointer to `@forSome`. It is what I was looking for.

Is controlled backward chaining useful from the end user perspective or is it only useful inside the implementation of EYE itself? Are there any simple examples of it being used in practice?

**Comment by josd** [comment]
In https://github.com/josd/eye/tree/master/reasoning there are examples of controlled chaining and `<=` rules are typically used as if they would be built-ins.

**Comment by logicReasoner** [comment]
@josd yeah, I've tried looking at the examples in https://github.com/josd/eye/tree/master/reasoning a few times in the past, but they often lack a concrete problem description and / or explanation of how the solution has been developed. And just looking at the source code is often not enough for a newcomer to understand what's going on. I think the EYE project could benefit tremendously from more detailed documentation.

Thanks again for your hard work! :+1:
