### ISSUE TITLE
/2004/04test/rogier

### ISSUE THREAD

**Issue by jmikedupont2** [eyereasoner/eye#8]
Hello Jos, Long long time no see.

The expression of atom in owl here 
http://bblfish.net/work/atom-owl/2006-06-06/# 
references a link 
 @prefix cifp: <http://eulersharp.sourceforge.net/2004/04test/rogier#>.
which is no longer available at that location. 

I found it here 
http://eulersharp.sourceforge.net/2004/04test/rogier.n3

and was wondering if you can add a symlink for that?
Thanks!

mike

**Comment by josd** [comment]
Thanks Mike, is indeed a long long time no see :-)
The symbolic link is available and should work.
