### ISSUE TITLE
wrong format for data types when parsing turtle

### ISSUE THREAD

**Issue by giacomociti** [eyereasoner/eye#83]
calling: `eye --nope --quiet --turtle data.ttl --query query.n3`

with the following data and query files:
```turtle
# data.ttl
@prefix : <http://ex.org/> .

:foo :height "6.0"^^<http://www.w3.org/2001/XMLSchema#decimal> ;
    :width 2.5 .
```

```
# query.n3
{ ?s ?p ?o } => { ?s ?p ?o } .
```

I get invalid literals (the data type is formatted with double quotes instead of angle brackets):
```turtle
<http://ex.org/foo> <http://ex.org/height> "6.0"^^"http://www.w3.org/2001/XMLSchema#decimal".
<http://ex.org/foo> <http://ex.org/width> "2.5"^^"http://www.w3.org/2001/XMLSchema#decimal".
```

Removing the `--turtle` option: `eye --nope --quiet data.ttl --query query.n3` solves the problem:
```turtle
@prefix : <http://ex.org/>.

:foo :height 6.0 .
:foo :width 2.5 .
```
Also, adding the `--no-numerals` option: `eye --nope --quiet  data.ttl --query query.n3 --no-numerals` the result is correctly formatted (albeit the decimal type becomes double):
```turtle
@prefix : <http://ex.org/>.

:foo :height "6.0"^^<http://www.w3.org/2001/XMLSchema#double> .
:foo :width "2.5"^^<http://www.w3.org/2001/XMLSchema#double> .
```

Since the turtle parser is significantly faster, I would like to use it. Is this a bug or I'm missing something?

**Comment by josd** [comment]
EYE v3.12.2 should now give
```
$ eye --nope --quiet --turtle data.ttl --pass
<http://ex.org/foo> <http://ex.org/height> 6.0 .
<http://ex.org/foo> <http://ex.org/width> 2.5 .
```
