### ISSUE TITLE
string:matches repeat expression does not work

### ISSUE THREAD

**Issue by tpluscode** [eyereasoner/eye#84]
I tried to match a string against the pattern `^\d{4}$` to recognise year values. Apparently, the `{4}` expression silently fails

```diff
@prefix : <https://example.com/> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .
@prefix string: <http://www.w3.org/2000/10/swap/string#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:ex1 :from "2000" .
:ex2 :from "-10" .
{
   ?s :from ?from .
   (
       {
-          ?from string:matches "^\\d{4}$" .
+          ?from string:matches "^\\d\\d\\d\\d$" .
       }
       {
           ( ?from xsd:gYear ) log:dtlit ?fromYear .
       }
       {
           ?fromYear log:equalTo ?from 
       }
   ) log:ifThenElseIn ?S .
}
=> 
{
   ?s :fromDate ?fromYear 
} .
```

**Comment by josd** [comment]
We lost that capability since https://github.com/eyereasoner/eye/blob/2664f8172a71199b66379f783733d4dbdde46573/eye.pl where we could use a C library which is not supported in swipl-wasm. We wanted to have a unified code base for both native swipl eye and swipl-wasm eye and so we had to switch back to a prolog based implementation that is inspired by http://www.cs.sfu.ca/~cameron/Teaching/384/99-3/regexp-plg.html and that does not support the `{m,n}` syntax.

**Comment by rybesh** [comment]
@josd Is there documentation of what regex features the prolog-based implementation supports?

**Comment by josd** [comment]
It supports what is described in https://www2.cs.sfu.ca/~cameron/Teaching/384/99-3/regexp-plg.html
One day we hope to move again to https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/pcre.html%27)

**Comment by rybesh** [comment]
> One day we hope to move again to https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/pcre.html%27)

Are there technical blockers preventing this from happening, or is it just a matter of time and labor? If it is the latter, I would be interested in helping out.

**Comment by josd** [comment]
It is technical and @jeswr and @JanWielemaker are quite close to get is working https://github.com/SWI-Prolog/npm-swipl-wasm/pull/143

**Comment by josd** [comment]
It should now work fine with the latest eye-js
```
$ sudo npm install -g eyereasoner
```
```
$ eyereasoner --version
eye --version
EYE v3.24.3 (2023-05-18)
SWI-Prolog version 9.1.10
```
```
$ cat t3.n3
@prefix : <https://example.com/> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .
@prefix string: <http://www.w3.org/2000/10/swap/string#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:ex1 :from "2000" .
:ex2 :from "-10" .
{
   ?s :from ?from .
   ?from string:matches "^\\d{4}$" .
   ( ?from xsd:gYear ) log:dtlit ?fromYear .
}
=>
{
   ?s :fromDate ?fromYear
} .
```
```
$ eyereasoner --quiet --nope t3.n3 --pass-only-new
@prefix : <https://example.com/>.
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix string: <http://www.w3.org/2000/10/swap/string#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

:ex1 :fromDate "2000"^^xsd:gYear.
```
