### ISSUE TITLE
Support non-capture groups in regular expressions

### ISSUE THREAD

**Issue by rybesh** [eyereasoner/eye#85]
Since [the switch to a non-PCRE regular expression implementation](https://github.com/eyereasoner/eye/issues/84), eye no longer supports [non-capture groups](https://www.pcre.org/current/doc/html/pcre2syntax.html#SEC13) in regular expressions. This makes it rather difficult to use eye for non-trivial string parsing using regular expressions, given that the spec for `string:scrape` stipulates that regular expressions may only contain a single capture group. It is often necessary to use groups in regular expressions, even if they are not being used to capture—but currently eye makes this impossible.

As a real-world use case of building up complex regular expressions from simpler regular expressions using `string:concatenation` that relies heavily on non-capture groups, see:

https://github.com/periodo/edtf-ontology/blob/main/rules/regexes.n3
https://github.com/periodo/edtf-ontology/blob/main/rules/common.n3

**Comment by josd** [comment]
There is now PCRE support in eye-js so it should now work like the naticv eye.
See also https://github.com/eyereasoner/eye/issues/84#issuecomment-1555929771

**Comment by rybesh** [comment]
@josd I am so happy to hear this. Thank you for your work!

**Comment by josd** [comment]
It is both @jeswr and @JanWielemaker who did the real work :-)
