### ISSUE TITLE
Increasing stack_limit for eye.pvm

### ISSUE THREAD

**Issue by bdevloed** [eyereasoner/eye#87]
I'm currently hitting resource limits with eye.

What I tried first was to add `--stack-limit` flag when calling eye, but this seems to have no effect when using eye.pvm?

```
swipl --stack-limit=8G -x /usr/local/lib/eye.pvm -- ...
```
Still gives:
```
error(resource_error(stack),stack_overflow{choicepoints:17,depth:485165,environments:485153,globalused:653824,localused:72019,non_terminating:[frame(485156,user:statements_optional(_167379224,[625122],_167379228),[]),frame(485155,user:statements_optional(_167379252,[625126],_167379256),[])],stack_limit:1048576,trailused:183301})
```
where the stack limit in the error still looks like the default 1G.

So am I correct that the only way to get this working is changing `eye.pl` code around here https://github.com/eyereasoner/eye/blob/9e1d1acda63286b4197cc34566269748fc73691b/eye.pl#L439 to set the https://www.swi-prolog.org/pldoc/doc_for?object=qsave_program/2 default `stack_limit`, before creating `eye.pvm`?

Thanks in advance,

eye and swipl versions:
EYE v23.0106.2349 josd
SWI-Prolog version 8.2.4

**Comment by josd** [comment]
Could you first try it with the latest versions?
```
EYE v3.23.0 (2023-05-11)
SWI-Prolog version 9.1.9
```
If same problem, could you then try it giving the `--stack-limit` argument in line 66 of https://github.com/eyereasoner/eye/blob/master/install.sh ?

**Comment by bdevloed** [comment]
Thanks a lot! In the end changing the stack limit in `install.sh` worked.
