### ISSUE TITLE
Strange result with RDF* annotation syntax

### ISSUE THREAD

**Issue by pchampin** [eyereasoner/eye#9]
```
@prefix : <#>.
:a is :b of :c {| :d :e |}.
```
produces
```
:c :b :a.
<<:a "isof('<file:///home/pa/recherche/2020-mosaicrown/policy_rdfstar/test.n3#b>')" :c>> :d :e.
```
The `isof(...)` in the embedded triple looks like internal representation leaking. I was expecting
```
:c :b :a.
<<:c :b :a>> :d :e.
```
@gkellogg

**Comment by josd** [comment]
Thanks very much @pchampin !
It should now work fine with https://github.com/josd/eye/releases/tag/v21.0119.1732
