### ISSUE TITLE
Support of property list in RDF Surfaces?

### ISSUE THREAD

**Issue by renyuneyun** [eyereasoner/eye#91]
I'm testing out RDF Surfaces. Most things work as expected, but one thing does not: property list is not recognized in it. For example, assume the following data:

```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix : <http://example.org/ns#>.

:a a :Data;
	:from [:uri <https://a.b>].
```

If query using this, the result will be empty:

```
(_:a _:b) log:onQuerySurface {
	_:a a :Data;
		:from [:uri _:b].
}.
```

While if using the following, the result will contain the data, as expected:

```
(_:a _:b _:c) log:onQuerySurface {
	_:a a :Data;
		:from _:c.
	_:c :uri _:b.
}.
```

So, is property list not supported, or is this a missing feature?

**Comment by josd** [comment]
It is not supported in n3s because surfaces require explicit quantification in their graffiti.
Also [Resource Paths](https://w3c.github.io/N3/reports/20230703/#paths) are not supported for the same reason.

**Comment by renyuneyun** [comment]
Thanks! It's good to know the reason behind it.
