### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by giacomociti** [eyereasoner/eye#98]
The following rule (a stripped down version of something more useful)
```turtle
@prefix : <http://example.org/> .
@prefix string: <http://www.w3.org/2000/10/swap/string#> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .

<s> <p> """<>>
""".

{
    ?s ?p ?o  .
    [] log:notIncludes { ?o [] [] } .
    (?value []) log:dtlit ?o .

    ( ?value
      ("<" ">") 
      ("&lt;" "&gt;" )
    ) string:replaceAll ?escapedValue .
}
=>
{
    ?s :value ?escapedValue
}
.
```
gives a strange error, reproducible [online](https://n3-editor.herokuapp.com/n3/editor/s/h9h9OMvc).

The error disappears as soon as we remove the newline in the data literal: https://n3-editor.herokuapp.com/n3/editor/s/zPLHInEh

**Comment by josd** [comment]
Thanks for finding and it should be fixed in `EYE v8.0.5 (2023-11-01)`
